### ISSUE TITLE
Cannot find test project even if project exists in solution

### ISSUE THREAD

**Issue by katdti** [sentryone/unittestgenerator#19]
Extension Version: 1.0.26
Visual Studio 2017 (15.9.13)

"Goto project" and "Generate tests for type ..." does not locate project if test project is located in a side or sub folder to the source folder like this:

> /src/X/Y/Y.ProjectZ/...
> /src/X/Y/Y.Tests/Y.ProjectZ.Tests...
> /src/solution.sln

or

> /src/X.ProjectY/...
> /src/solution.sln
> /test/X.ProjectY.Tests/...

It seems it only can find test if solution (sln) file is located like this:

> /src/X.ProjectY/...
> /src/solution.sln
> /src/X.Tests/X.ProjectY.Tests/...
 

Sample Solution:
[SentryOne.zip](https://github.com/sentryone/unittestgenerator/files/4248868/SentryOne.zip)

Screen dump of error message:
![image](https://user-images.githubusercontent.com/39122119/75229358-0cdfa500-57b2-11ea-9e1a-f6faffa987aa.png)

**Comment by mattwhitfield** [comment]
Hello

Thanks for the report - I can't repro this - as long as the projects are loaded and in the same solution then it will find them by project name, not by project path. Would you be able to clarify a bit further so I can reproduce the issue you are having?

Thanks for your feedback!

Matt

**Comment by katdti** [comment]
Sample solution and screen dump added to original issue

**Comment by mattwhitfield** [comment]
Thanks for that, I had made a stupid mistake implementing the folder walking. A new release will be out soon.

**Comment by mattwhitfield** [comment]
1.0.27 is now available which should address the issue. If you wouldn't mind confirming the fix here I'd appreciate it. Thanks again for your help!

**Comment by katdti** [comment]
Extension version 1.0.27 now finds the test project in the Sample Solution supplied in the original issue note.
