### ISSUE TITLE
Generating test for new method in generic class regenerate tests for the whole class

### ISSUE THREAD

**Issue by katdti** [sentryone/unittestgenerator#21]
Extension version 1.0.27

Sample Solution:   
[SentryOne.zip](https://github.com/sentryone/unittestgenerator/files/4250409/SentryOne.zip)

Menu screen dump:
![image](https://user-images.githubusercontent.com/39122119/75255819-d1a99a00-57e2-11ea-8921-cca9081d58df.png)

Result Code:
![image](https://user-images.githubusercontent.com/39122119/75255833-da9a6b80-57e2-11ea-96ac-671ad578d754.png)

**Comment by mattwhitfield** [comment]
1.0.28 is now in the marketplace and addresses this issue. Thanks for bringing it to our attention!
