### ISSUE TITLE
Cannot install on Visual Studio 2019 version 16.11.2

### ISSUE THREAD

**Issue by kristofferjalen** [sentryone/unittestgenerator#49]
I guess it's because the current value of supported versions is `[15.0,19.0)` but [should be](https://devblogs.microsoft.com/visualstudio/visual-studio-extensions-and-version-ranges-demystified/) `[15.0,17.0)`.

**Comment by mattwhitfield** [comment]
Can you give me a bit more info about why it doesn't install for you? Because I have it running on 16.11.2 just fine - but had a couple of issues like this now so would like to get to the bottom of it

**Comment by kristofferjalen** [comment]
I managed to successfully install the extension after having modified the `.vsixmanifest` file:

From:
```
<InstallationTarget Version="[15.0, 19.0)" Id="Microsoft.VisualStudio.Pro" />
```
To:
```
<InstallationTarget Version="[15.0, 17.0)" Id="Microsoft.VisualStudio.Pro" />
```
But it's strange, because on another computer I could install it.

**Comment by mattwhitfield** [comment]
Yeah, I managed to repro it on a machine - and it really shouldn't be like that. The version spec says `[15.0, 19.0)` should be fine. `¯\_(ツ)_/¯`

I'll make the changes when I can next update the extension.

**Comment by kristofferjalen** [comment]
And for VS 2022 as well.

**Comment by mattwhitfield** [comment]
Fixed in https://marketplace.visualstudio.com/items?itemName=MattWhitfield.Unitverse - please open a new issue on https://github.com/mattwhitfield/unittestgenerator/issues if there is still a problem 👍
